# Generated by Django 6.0.1 on 2026-01-08 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Tiền mặt'), ('MOMO', 'MoMo'), ('ZALOPAY', 'ZaloPay'), ('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal')], default='CASH', max_length=50),
        ),
    ]
