# Generated by Django 6.0 on 2026-01-05 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_tag_bookmark_lesson_bookmark_users_lesson_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.comment'),
        ),
    ]
